# Generated by Django 4.1.5 on 2023-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
